name: ze_delivery
channels:
  - conda-forge
  - anaconda
dependencies:
  - python==3.6.5
  - matplotlib==3.3.4
  - seaborn==0.11.0
  - pandas==0.24.2
  - ipykernel==5.3.4
  - pathlib==1.0.1
  - xlrd==1.2.0
  - pip
  - pip:
    - XlsxWriter==1.3.7
    - -e .